# Generated by Django 3.2.3 on 2021-06-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstock',
            name='ori_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstock',
            name='volume',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
