# Generated by Django 3.2.3 on 2021-06-07 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210605_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstock',
            name='ori_price',
        ),
        migrations.AddField(
            model_name='user',
            name='equity',
            field=models.IntegerField(default=100000),
        ),
    ]
